#cloud-config
users:
-   name: future
    groups: sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    lock_passwd: true
    plain_text_passwd: 'password'
# login SSH and console with password
    ssh_pwauth: true
    disable_root: false 
# Install pakage
packages:
    - mysql-server
package-update: true
package_upgrade: true
write_files:
 - content: |
    CREATE USER 'futuresql'@'localhost' IDENTIFIED BY 'password';
    CREATE USER 'futuresql'@'%' IDENTIFIED BY 'password';
    GRANT ALL ON *.* TO 'futuresql'@'localhost';
    GRANT ALL ON *.* TO 'futuresql'@'%';
    FLUSH PRIVILEGES;
   path: /tmp/initdb.sql
   permissions: '0644' 
runcmd:
#MySQL
 - 'sudo mysql </tmp/initdb.sql'
  - sudo rm /tmp/initdb.sql 
  - sudo sed -i -e"s/^bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
  - sudo systemctl restart mysql
# SSH
    - sed -i -e '/^Port/s/^.*$/Port 22/' /etc/ssh/sshd_config
    - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
    - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
    - sed -i -e '$aAllowUsers dev' /etc/ssh/sshd_config
    - sudo service ssh restart
# Firewall
    # defaults
    - sudo ufw default deny incoming
    - sudo ufw default allow outgoing
    # exceptions
    - sudo ufw allow ssh
    - sudo ufw allow http
    - sudo ufw allow https
    # start on boot
    - sed -i -e '/^ENABLED/s/^.*$/ENABLED=yes/' /etc/ufw/ufw.conf
    - sudo ufw enable