#cloud-config installiert Webserver mit simplen PHP Text
packages:
- apache2 
- php 
- libapache2-mod-php 
#PHP Text definition mit Berechtigung
write_files:
- content: |
    <?php echo '<p>Project Future Faild Successfully</p>'; ?>
  path: /var/www/html/index.php
  permissions: '0644'